Плаксин Иван
urfu-2018/markup-task-9 pull request #11
Opened 2018-12-05 11:51 UTC by ZeroNetto

[Посмотреть решение](https://hruview.herokuapp.com/ZeroNetto/markup-task-9/master/index.html)

2018-12-05 11:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-05 16:45 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-12 05:12 UTC, chrighter requested changes
🍅

2018-12-12 05:12 UTC, chrighter commented on index.css
> +    font-family: Helvetica;
А если у пользователя не будет такого шрифта? Давай добавим хотя бы семейство

2018-12-12 05:12 UTC, chrighter commented on index.html
> +                    <img alt="cat" src="./images/cap.jpg" class="preview">
cap?

2018-12-12 05:15 UTC, chrighter requested changes

2018-12-12 05:15 UTC, chrighter commented on index.html
> +            <div class="settings">
Предполагалось, что все иконки будут сделаны через `svg`-спрайты.
Желательно, чтобы это был один `svg`-файл, который будет подключаться в `CSS` как `background` и двигаться через `background-position`

2018-12-13 18:02 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2019-01-04 20:32 UTC, chrighter approved these changes

2019-01-04 20:32 UTC, closed without merging