Солодовникова Екатерина
urfu-2018/markup-task-9 pull request #22
Opened 2018-12-05 19:25 UTC by KatySolo

[Посмотреть решение](https://hruview.herokuapp.com/KatySolo/markup-task-9/master/index.html)

2018-12-05 19:26 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-09 13:39 UTC, chrighter requested changes
🍅

2018-12-09 13:39 UTC, chrighter commented on index.css
> +    /*content: url('cat.jpg');*/
Лишние комментарии ((

2018-12-09 13:39 UTC, chrighter commented on index.css
> +
Лишняя строка

2018-12-09 13:39 UTC, chrighter commented on icons/scale.svg
> +<svg width="48" height="48" xmlns="http://www.w3.org/2000/svg"><path d="M0 0v48h48V0H0zm6.4 6.4h33.682L6.4 40.227V6.4zm34.56 32.427H25.6v-6.4h15.36v6.4z"/><path d="M24 13.071h-4.375v-4.5h-6.25v4.5H9V
Это используется?

2018-12-09 13:39 UTC, chrighter commented on index.html
> +<div class="filters-menu">
Давай семантику добавим

2018-12-12 10:06 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-13 05:57 UTC, chrighter approved these changes
🍏

2018-12-13 05:57 UTC, closed without merging