Петрова Дарья
urfu-2018/markup-task-9 pull request #6
Opened 2018-12-04 16:40 UTC by PetrovaDaria

Градиент на логотипе никак не получается(

2018-12-04 16:41 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-12-04 16:45 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-05 08:22 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-15 21:48 UTC, spt30 requested changes
🍅Привет! Есть пара замечаний:

1) У тебя есть просмотр исходного изображения, но с точки зрения юзера, вообще не понятно, что сейчас идет просмотр превью (при этом все кнопки визуально ничего не меняют) Давай либо реализуем просмотр превью в виде модального окна, которое можно закрыть
либо при просмотре превью меняем вид кнопки, чтобы было видно, что она нажата, а также задизейблим все остальные контролы

2) Есть проблема с семантикой, все на дивах (тут ее не надо слишком много, просто части контента разделить достаточно)

Карусель реализована классно, молодец!

Дедлайна + неделя и 30 часов с текущего времени: 24 декабря 9:00

2018-12-15 21:48 UTC, spt30 commented on index.css
> +    font-family: 'Helvetica';
А если у меня все же ОС, на которой нет Гельветики?

2018-12-23 06:06 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-23 11:26 UTC, spt30 commented
🍏
Было все на div'ах, теперь все на section'ах)))
И не реализовала на кнопке просмотра превью модификатор стиля для того, чтобы было видно, что кнопка нажата

Ну дело твое, тут уж не столь критично, это скорее просто рекомендации

2018-12-23 11:26 UTC, closed without merging

2018-12-23 11:58 UTC, PetrovaDaria commented
такое чувство, что я все еще до конца не понимаю, где нужен div, где section, а где article... там не так уже много дивов было...

2018-12-23 12:22 UTC, spt30 commented
@PetrovaDaria 
![image](https://user-images.githubusercontent.com/31798669/50383477-24b32900-06d6-11e9-8ae7-00cfcead6391.png)
Это должно помочь, в 90% случаев это так работает

По существу, логика такая: 
1) Думаешь, структурный элемент или нет (article – структурный, p – не структурный)
2) Если не структурный – выбираешь, какой надо
Если струкрутный, едешь на п.3 
3) Если ты прям видишь специальный тег, например nav, aside, header..., ставишь его, если не понятно, идем дальше
4) section – это часть страницы или часть какого-то блока (зависит от того, куда вложен), например
```
<body>
    <header>
        <section class="1" /> 
    </header>
    <main>
        <section class="2" />
        <section class="3">
            <section class="4" /> 
            <section class="5" /> 
        </section>
    </main>
</body>
``` 
Тут, например, section.1 будет частью шапки страницы, section.2 и section.3 – части main (читай "всей страницы"), section.4 и section.5 – части section.3

5) article – это самостоятельная часть страницы, которую можно переиспользовать или перенести в другое место без потери понятности

6) div – если ни 1, ни 2, ни 3, ни 4, ни 5 пункт не подошли

2018-12-23 12:23 UTC, spt30 commented
Можешь посмотреть пару докладов Макеева:
1) Очень старый, когда только вышла 5-я версия html, тут подробно рассказано, какой тег и где юзать: https://www.youtube.com/watch?v=a-igZjv9P4o
2) Новый доклад, где рассказывается, зачем все это надо (или не надо): https://www.youtube.com/watch?v=W5DgVWtitjQ

2018-12-23 12:24 UTC, PetrovaDaria commented
спасибо!

2018-12-23 12:37 UTC, spt30 commented
Можешь для себя привести такую аналогию: article – это как padding, section – это как margin
article отвечает за внутреннее содержание, как padding за внутренние отступы
section отвечает за соотношение с соседними блоками, как margin за внешние отступы